package com.kingstreet.gilaki.ui

data class Copy(
    val title: String,
    val subtitle: String,
    val record: String,
    val stop: String,
    val chooseFile: String,
    val ready: String,
    val recording: String,
    val uploading: String,
    val error: String,
    val maps: String,
    val settings: String,
    val showSounds: String,
    val hideSounds: String,
    val apiBase: String,
    val language: String,
    val english: String,
    val persian: String,
    val customMap: String,
    val customHint: String,
    val saveMap: String,
    val saveSettings: String,
    val applyServer: String,
    val lossy: String,
    val noResult: String,
)

fun copy(lang: String): Copy = if (lang == "fa") FA else EN

private val EN = Copy(
    title = "Gilaki",
    subtitle = "Speech to writing. Audio stays on this device.",
    record = "Record",
    stop = "Stop",
    chooseFile = "Choose file",
    ready = "Ready",
    recording = "Recording…",
    uploading = "Uploading…",
    error = "Something went wrong",
    maps = "Maps",
    settings = "Settings",
    showSounds = "Show sounds",
    hideSounds = "Hide sounds",
    apiBase = "API base URL",
    language = "Interface language",
    english = "English",
    persian = "Persian",
    customMap = "Custom map (this device only)",
    customHint = "JSON is saved on this phone, not on the server.",
    saveMap = "Save map",
    saveSettings = "Save",
    applyServer = "Apply this custom map on the server for the next upload",
    lossy = "This map collapses Gilaki vowels.",
    noResult = "Record or choose a file to transcribe.",
)

private val FA = Copy(
    title = "گیلکی",
    subtitle = "گفتار به نوشتار. صدا روی همین دستگاه می‌ماند.",
    record = "ضبط",
    stop = "توقف",
    chooseFile = "انتخاب پرونده",
    ready = "آماده",
    recording = "در حال ضبط…",
    uploading = "در حال ارسال…",
    error = "خطا رخ داد",
    maps = "نقشه‌ها",
    settings = "تنظیمات",
    showSounds = "نمایش صداها",
    hideSounds = "پنهان کردن صداها",
    apiBase = "نشانی پایهٔ API",
    language = "زبان رابط",
    english = "انگلیسی",
    persian = "فارسی",
    customMap = "نقشهٔ سفارشی (فقط روی این دستگاه)",
    customHint = "JSON روی همین گوشی ذخیره می‌شود، نه روی سرور.",
    saveMap = "ذخیرهٔ نقشه",
    saveSettings = "ذخیره",
    applyServer = "برای بارگذاری بعدی این نقشهٔ سفارشی روی سرور اعمال شود",
    lossy = "این نقشه واکه‌های گیلکی را ساده می‌کند.",
    noResult = "ضبط کنید یا پرونده‌ای انتخاب کنید.",
)
